name: smart_spent_story
description: A smart personal finance tracker built with Clean Architecture.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Networking
  dio: ^5.7.0

  # Dependency Injection
  get_it: ^8.0.2

  # Navigation
  go_router: ^14.6.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4

  # Functional Programming
  dartz: ^0.10.1

  # Charts
  fl_chart: ^0.70.2

  # UI & Styling
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.19.0
  logger: ^2.5.0
  connectivity_plus: ^6.1.1

  # Icons
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # bloc_test: ^9.1.7
  mocktail: ^1.0.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
